language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # building
  # - docker-compose -f docker-compose-build.yaml build --parallel
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  
  # tagging
  - docker tag udagram-api-feed 11223030/udagram-api-feed:v1
  - docker tag udagram-api-user 11223030/udagram-api-user:v1
  - docker tag reverseproxy 11223030/reverseproxy:v1
  - docker tag udagram-frontend 11223030/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push 11223030/udagram-api-feed:v1
  - docker push 11223030/udagram-api-user:v1
  - docker push 11223030/reverseproxy:v1
  - docker push 11223030/udagram-frontend:v1