apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVROVU9PN01NR0tXWUNHWEYK
  AWS_SECRET_ACCESS_KEY: ZUtjc2VhSk5wd3VFWFBLK29zWEthbC9SRDJqYW12eHVLTE0wb0VnMjEK
  AWS_SESSION_TOKEN: RndvR1pYSXZZWGR6RUtMLy8vLy8vLy8vL3dFYURESkZzMUVLMkpFMWUrZUl4aUxWQVdyekM5Yk1ad2lvNWRUL1g1ODJ3WHZ2NFhoMGFPV2JSeDNjMkUwQU5xWCtmVEpLeWp0enRLcHdjdmFoQXhkdE5xbHNqL3JxNHB1b09lN3JENFB6aFJ1TTBkQTdOQ01XYU5JR0xJZmNHU3JlMWFERUM1ZlhRS05MT3dSUWoxdm83N1M3akxoYXo2dzAzSTdvMnl4bHAvUXpWZlhUS0RBUGpVcUI0NjVhMXdhNWU1T1VySi8rV0hkYnpheFROekdodWx6TjhmQi95NFN6MEF6UEpiQ2tMUGVHRTNxUVFGQ0lwMjRiVUZaSllHcUVQUWlaRE5KbDU3R2NxR0xnSVlWS24vd1UvbzczVnNrQ3AvTWdKTnNOY0I4eTRwTnR0U2lOdlkrYUJqSXRMZ1AxUmV0U0dyeDFxWWtZTk5BTWNtdTRCYWt3TmtKb3hBMzFuWURLcmN0YThCTjZuOTNORzlVeHhaeFgK 